"""Foundational contracts and leaf evaluation for Milestone 4 sampled search."""

from innovation_ai.search.contracts import (
    DEFAULT_SEARCH_DESCRIPTOR,
    PRODUCTION_DETERMINIZATION_COUNT,
    PRODUCTION_ROUTE_TRANSITION_BUDGET,
    PRODUCTION_SEARCH_DESCRIPTOR,
    SEARCH_DESCRIPTOR_SCHEMA_VERSION,
    SEARCH_TELEMETRY_SCHEMA_VERSION,
    RootSelectionTelemetry,
    RootTelemetry,
    RouteTelemetry,
    SearchDescriptor,
    SearchRouteTelemetry,
)
from innovation_ai.search.evaluator import (
    EVALUATOR_VERSION,
    NEGATIVE_TERMINAL_SENTINEL,
    POSITIVE_TERMINAL_SENTINEL,
    TERMINAL_DRAW_SENTINEL,
    TERMINAL_LOSS_SENTINEL,
    TERMINAL_WIN_SENTINEL,
    HandEngineeredEvaluator,
    LeafEvaluation,
    TerminalOrdering,
    evaluate_leaf,
    evaluate_nonterminal,
    evaluate_nonterminal_components,
    evaluate_state,
    terminal_ordering,
    terminal_value,
)

__all__ = [
    "DEFAULT_SEARCH_DESCRIPTOR",
    "EVALUATOR_VERSION",
    "NEGATIVE_TERMINAL_SENTINEL",
    "POSITIVE_TERMINAL_SENTINEL",
    "PRODUCTION_DETERMINIZATION_COUNT",
    "PRODUCTION_ROUTE_TRANSITION_BUDGET",
    "PRODUCTION_SEARCH_DESCRIPTOR",
    "SEARCH_DESCRIPTOR_SCHEMA_VERSION",
    "SEARCH_TELEMETRY_SCHEMA_VERSION",
    "TERMINAL_DRAW_SENTINEL",
    "TERMINAL_LOSS_SENTINEL",
    "TERMINAL_WIN_SENTINEL",
    "HandEngineeredEvaluator",
    "LeafEvaluation",
    "RootSelectionTelemetry",
    "RootTelemetry",
    "RouteTelemetry",
    "SearchDescriptor",
    "SearchRouteTelemetry",
    "TerminalOrdering",
    "evaluate_leaf",
    "evaluate_nonterminal",
    "evaluate_nonterminal_components",
    "evaluate_state",
    "terminal_ordering",
    "terminal_value",
]
